def loadup():
    import time
    print('       ZZ___      ')
    time.sleep(.1)
    print('       ZZ___      ')
    time.sleep(.1)
    print('      ZZZZ___     ')
    time.sleep(.1)
    print('     ZZZZZZ___    ')
    time.sleep(.1)
    print('     ZZZZZZ___    ')
    time.sleep(.1)
    print('    ZZZZZZZZ___   ')
    time.sleep(.1)
    print('   ZZZZZZZZZ___   ')
    time.sleep(.1)
    print('  ZZZZ ZZZZZZ___  ')
    time.sleep(.1)
    print(' ZZZZZ  ZZZZZZ___ ')
    time.sleep(.1)
    print(' ZZZZZZ ZZZZZZ___ ')
    time.sleep(.1)
    print(' ZZZZZZ  ZZZZZZ___')
    time.sleep(.1)
    print('  ZZZZZZ ZZZZZZ___')
    time.sleep(.1)
    print('   ZZZZZ  ZZZZZ___')
    time.sleep(.1)
    print('   ZZZZZ ZZZZZZ___')
    time.sleep(.1)
    print('    ZZZ ZZZZZZ___ ')
    time.sleep(.1)
    print('      ZZZZZZ___   ')
    time.sleep(.1)
    print('     ZZZZZZ___    ')
    time.sleep(.1)
    print('     ZZZZZ___     ')
    time.sleep(.1)
    print('    ZZZZZZ  ZZ___ ')
    time.sleep(.1)
    print('   ZZZZZZ  ZZZZ___')
    time.sleep(.1)
    print('   ZZZZZ  ZZZZZ___')
    time.sleep(.1)
    print('  ZZZZZZ ZZZZZZ___')
    time.sleep(.1)
    print('  ZZZZZ  ZZZZZZ___')
    time.sleep(.1)
    print(' ZZZZZZ ZZZZZZ___ ')
    time.sleep(.1)
    print(' ZZZZZ  ZZZZZZ___ ')
    time.sleep(.1)
    print('  ZZZZ ZZZZZZ___  ')
    time.sleep(.1)
    print('   ZZZZZZZZZ___   ')
    time.sleep(.1)
    print('    ZZZZZZZZ___   ')
    time.sleep(.1)
    print('     ZZZZZZ___    ')
    time.sleep(.1)
    print('     ZZZZZZ___    ')
    time.sleep(.1)
    print('      ZZZZ___     ')
    time.sleep(.1)
    print('       ZZ___      ')
    time.sleep(.1)
    print('       ZZ___      ')
    time.sleep(.5)